@API_TOKEN_LOCAL = "token"
@API_BASE_URL_LOCAL = http://localhost:8000/api/v1


### Get my profile
GET {{API_BASE_URL_LOCAL}}/user/profile
Authorization: Bearer {{API_TOKEN_LOCAL}}

### Get all users
GET {{API_BASE_URL_LOCAL}}/user/users-list
Authorization: Bearer {{API_TOKEN_LOCAL}}

### Get all online users
GET {{API_BASE_URL_LOCAL}}/user/online-list
Authorization: Bearer {{API_TOKEN_LOCAL}}