export const Actions = {
  IS_SIDEBAR_OPEN: 'IS_SIDEBAR_OPEN',
  CHANGE_NAV_MAIN_ADMIN: 'CHANGE_NAV_MAIN_ADMIN',
  CHANGE_NAV_MAIN_STUDENT: 'CHANGE_NAV_MAIN_STUDENT',
  UPDATE_SIDEBAR_STATE: 'UPDATE_SIDEBAR_STATE',
  RESET_STATE: 'RESET_STATE',
};
