export const Actions = {
  IS_SIDEBAR_OPEN: 'IS_SIDEBAR_OPEN',
  UPDATE_SIDEBAR_STATE: 'UPDATE_SIDEBAR_STATE',
  SELECTED_USER_STATE: 'SELECTED_USER_STATE',
  SET_STREAM_STATE: 'SET_STREAM_STATE',
  RECIEVING_CALL_STATE: 'RECIEVING_CALL_STATE',
  CALLER_STATE: 'CALLER_STATE',
  RESET_STATE: 'RESET_STATE',
};
